/* Z1 Loot Database frontend. Reads window.LOOT_DB generated by extract.ts. */
(function () {
  const DB = window.LOOT_DB;
  const byId = new Map(DB.items.map((i) => [i.id, i]));

  const norm = (s) => String(s ?? "").toLowerCase().replace(/[^a-z0-9]/g, "");

  const CAT_ORDER = [
    "Guns", "Melee", "Ammo", "Medical", "Food & Drink", "Armor",
    "Clothing", "Materials", "Repair", "Construction", "Containers",
    "Skins & Unlocks", "Crates & Keys", "Emotes", "Other"
  ];
  const catCounts = {};
  for (const it of DB.items) catCounts[it.cat] = (catCounts[it.cat] || 0) + 1;

  const $ = (sel) => document.querySelector(sel);
  const content = $("#content");
  const esc = (s) =>
    String(s ?? "").replace(/[&<>"]/g, (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]
    );

  $("#meta").textContent =
    DB.meta.itemCount + " items · generated " +
    new Date(DB.meta.generatedAt).toLocaleDateString();

  // ------------------------------------------------------------------
  // Search
  // ------------------------------------------------------------------
  const searchIndex = DB.items.map((it) => ({
    it,
    n: norm(it.name),
    c: norm(it.code),
    id: String(it.id)
  }));

  function search(q) {
    const nq = norm(q);
    if (!nq) return [];
    const scored = [];
    for (const e of searchIndex) {
      let score = -1;
      if (e.n === nq || e.id === nq) score = 0;
      else if (e.n.startsWith(nq)) score = 1;
      else if (e.n.includes(nq)) score = 2;
      else if (e.c.includes(nq)) score = 3;
      if (score >= 0) scored.push({ e, score });
    }
    scored.sort(
      (a, b) =>
        a.score - b.score ||
        !!b.e.it.sources - !!a.e.it.sources ||
        a.e.n.length - b.e.n.length
    );
    return scored.slice(0, 30).map((s) => s.e.it);
  }

  const searchEl = $("#search");
  const resultsEl = $("#results");
  let activeIdx = -1;
  let currentResults = [];

  function renderResults() {
    if (!currentResults.length) {
      resultsEl.classList.add("hidden");
      return;
    }
    resultsEl.innerHTML = currentResults
      .map(
        (it, i) =>
          `<div class="row${i === activeIdx ? " active" : ""}" data-id="${it.id}">
            <span><span class="nm">${esc(it.name)}</span><span class="cd">#${it.id}${it.code ? " · " + esc(it.code) : ""}</span></span>
            <span class="badge ${esc(it.cat.split(" ")[0])}">${esc(it.cat)}</span>
          </div>`
      )
      .join("");
    resultsEl.classList.remove("hidden");
  }
  searchEl.addEventListener("input", () => {
    currentResults = search(searchEl.value);
    activeIdx = -1;
    renderResults();
  });
  searchEl.addEventListener("keydown", (ev) => {
    if (ev.key === "ArrowDown") { activeIdx = Math.min(activeIdx + 1, currentResults.length - 1); renderResults(); ev.preventDefault(); }
    else if (ev.key === "ArrowUp") { activeIdx = Math.max(activeIdx - 1, 0); renderResults(); ev.preventDefault(); }
    else if (ev.key === "Enter" && currentResults.length) {
      const it = currentResults[Math.max(activeIdx, 0)];
      go("#/item/" + it.id);
    } else if (ev.key === "Escape") { resultsEl.classList.add("hidden"); }
  });
  resultsEl.addEventListener("mousedown", (ev) => {
    const row = ev.target.closest(".row");
    if (row) go("#/item/" + row.dataset.id);
  });
  document.addEventListener("click", (ev) => {
    if (!ev.target.closest(".searchwrap")) resultsEl.classList.add("hidden");
  });

  function go(hash) {
    resultsEl.classList.add("hidden");
    searchEl.blur();
    location.hash = hash;
  }

  // ------------------------------------------------------------------
  // Sidebar
  // ------------------------------------------------------------------
  function renderSidebar(activeCat) {
    $("#sidebar").innerHTML =
      "<h3>Categories</h3>" +
      CAT_ORDER.filter((c) => catCounts[c]).map(
        (c) =>
          `<a class="cat${c === activeCat ? " active" : ""}" href="#/cat/${encodeURIComponent(c)}">
            <span>${esc(c)}</span><span class="n">${catCounts[c]}</span>
          </a>`
      ).join("");
  }

  // ------------------------------------------------------------------
  // Shared render helpers
  // ------------------------------------------------------------------
  const link = (id) => {
    const it = byId.get(id);
    return it
      ? `<a href="#/item/${id}">${esc(it.name)}</a>`
      : `<span class="cond">item #${id}</span>`;
  };
  const kv = (pairs) =>
    `<div class="kv">${pairs
      .filter((p) => p[1] !== undefined && p[1] !== null && p[1] !== "")
      .map((p) => `<span class="k">${p[0]}</span><span class="v">${p[1]}</span>`)
      .join("")}</div>`;
  const fmtCount = (c) => (c[0] === c[1] ? `${c[0]}` : `${c[0]}–${c[1]}`);
  const fmtMs = (ms) => (ms >= 1000 ? (ms / 1000).toFixed(1) + "s" : ms + "ms");

  function damageText(w) {
    const HP = DB.meta.playerMaxHealth;
    if (w.damage.kind === "flat") {
      const d = w.damage.value;
      const hs = d * w.headshotMultiplier;
      return kv([
        ["Body damage", `${d} <small>(${Math.ceil(HP / d)} shots to kill)</small>`],
        ["Headshot", `${hs} <small>(×${w.headshotMultiplier}, ${Math.ceil(HP / hs)} to kill)</small>`]
      ]);
    }
    const hsMax = w.damage.max * w.headshotMultiplier;
    return kv([
      ["Damage (falloff)", `${w.damage.max} → ${w.damage.min} <small>from ${w.damage.startM}m to ${w.damage.endM}m</small>`],
      ["Headshot", `up to ${hsMax} <small>(×${w.headshotMultiplier})</small>`]
    ]);
  }

  function weaponCard(it) {
    const w = it.weapon;
    const ammoIds = [...new Set(w.modes.map((m) => m.ammoId))];
    const m = w.modes[0];
    const rows = w.modes
      .map(
        (fm) =>
          `<tr><td>${fm.rpm} RPM</td><td>${fmtMs(fm.reloadMs)}</td><td>${fm.range}m</td><td>${fm.pellets || "—"}</td></tr>`
      )
      .join("");
    const dps =
      it.weapon.damage.kind === "flat"
        ? Math.round((w.damage.value * m.rpm) / 60)
        : null;
    return `<div class="card"><h2>Weapon — ${esc(w.defName || "")}</h2>
      ${damageText(w)}
      <div style="height:10px"></div>
      ${kv([
        ["Ammo", ammoIds.map(link).join(", ")],
        ["Magazine", w.clipSize],
        ["Fire rate", m.rpm + " RPM" + (dps ? ` <small>(~${dps} dmg/s)</small>` : "")],
        ["Reload", fmtMs(m.reloadMs)],
        ["Range", m.range + "m"],
        m.pellets ? ["Pellets/shot", m.pellets] : ["", ""]
      ])}
      ${w.modes.length > 1 ? `<div style="height:12px"></div><table class="tbl"><tr><th>Mode (RPM)</th><th>Reload</th><th>Range</th><th>Pellets</th></tr>${rows}</table>` : ""}
      <div class="note">Damage vs players; armor and helmets reduce it. Values from <code>getProjectileDamage()</code> and ServerWeaponDefinitions.</div>
    </div>`;
  }

  function meleeCard(it) {
    const HP = DB.meta.playerMaxHealth;
    const d = it.melee.damage;
    return `<div class="card"><h2>Melee</h2>
      ${kv([
        ["Damage / swing", `${d} <small>(${Math.ceil(HP / d)} hits to kill)</small>`],
        ["Headshot", `${d * it.melee.headshotMultiplier} <small>(×${it.melee.headshotMultiplier})</small>`]
      ])}
      <div class="note">Base melee 1000 × weapon multiplier (abilitiesmanager.ts).</div>
    </div>`;
  }

  function useCard(it) {
    const rows = it.use.map((u) => {
      const effects = [
        ["Energy", u.eat], ["Hydration", u.drink], ["Comfort", u.comfort],
        ["Health", u.heal], ["Bandaging", u.bandaging]
      ].filter((e) => e[1]);
      return `<div class="recipe">
        <div class="rhead">${esc(u.type.replace(/_/g, " "))}${u.timeout ? " · " + fmtMs(u.timeout) : ""}${u.healType ? " · " + esc(u.healType) : ""}</div>
        ${kv(effects.map((e) => [e[0], "+" + e[1]]))}
        ${u.givetrash ? `<div class="cond" style="margin-top:6px">Leaves behind: ${link(u.givetrash)}</div>` : ""}
      </div>`;
    });
    return `<div class="card"><h2>Use effects</h2>${rows.join("")}</div>`;
  }

  function recipeBlock(r) {
    const req = [
      r.workbench ? "Workbench" : null,
      r.weaponWorkbench ? "Weapon workbench" : null,
      r.kind === "smelt" ? (r.filter === "COOKING" ? "Campfire / BBQ" : "Furnace") : null
    ].filter(Boolean);
    return `<div class="recipe">
      <div class="rhead">${r.kind === "smelt" ? "Cook / smelt" : "Craft"}${r.bundle ? ` ×${r.bundle}` : ""} — filter: ${esc(r.filter)}${req.length ? " · requires " + req.join(" + ") : ""}</div>
      <ul>${r.components.map((c) => `<li>${c.amount}× ${link(c.id)}</li>`).join("")}</ul>
      ${r.leftOver ? `<div class="cond">Left over: ${r.leftOver.map(link).join(", ")}</div>` : ""}
    </div>`;
  }

  function craftCard(it) {
    let html = "";
    if (it.craftedBy) html += it.craftedBy.map(recipeBlock).join("");
    if (it.usedIn && it.usedIn.length) {
      html += `<div class="rhead" style="margin-top:10px;color:var(--muted);font-size:.8rem">Used to craft:</div>
        <div class="chips" style="margin-top:6px">${it.usedIn.map((id) => `<span class="chip">${link(id)}</span>`).join("")}</div>`;
    }
    return html ? `<div class="card"><h2>Crafting</h2>${html}</div>` : "";
  }

  function repairCard(it) {
    if (!it.durability && !it.repair) return "";
    const rows = [["Max durability", it.durability]];
    return `<div class="card"><h2>Durability & repair</h2>
      ${kv(rows)}
      ${it.repair ? `<div style="height:10px"></div><table class="tbl"><tr><th>Repair with</th><th>Effect</th></tr>${it.repair
        .map((r) => `<tr><td>${link(r.id)}</td><td>${esc(r.effect)}</td></tr>`)
        .join("")}</table>` : ""}
      ${it.weapon ? `<div class="note">Weapons break into ${link(1354)} at 0 durability.</div>` : ""}
    </div>`;
  }

  function chanceText(s) {
    let main = `<span class="pct">${s.sharePct}%</span>`;
    const extra = [];
    if (s.kind === "ground") {
      extra.push(`spawn point fill: ${s.spawnChance}%`);
      main += ` <span class="cond">of pool</span>`;
    } else if (s.rolls) {
      main += ` <span class="cond">per roll</span>`;
      extra.push(`${s.rolls[0]}–${s.rolls[1]} rolls`);
    }
    if (s.via) extra.push("via " + s.via.join(" → "));
    return main + (extra.length ? `<div class="cond">${extra.join(" · ")}</div>` : "");
  }

  function sourceName(s) {
    if (s.kind === "zombie") return esc(s.table);
    let n = s.table
      .replace(/^ItemSpawner_?/, "")
      .replace(/\.adr$/, "")
      .replace(/_/g, " ");
    if (s.kind === "airdrop") n += " airdrop";
    return esc(n) + (s.worldCount ? ` <span class="cond">(${s.worldCount} in world)</span>` : "");
  }

  function collectMapGroups(it) {
    const groups = [];
    const seen = new Set();
    for (const s of it.sources || []) {
      if (s.posKey && !seen.has(s.posKey) && DB.positions[s.posKey]) {
        seen.add(s.posKey);
        const label = s.table
          .replace(/^ItemSpawner_?/, "")
          .replace(/\.adr$/, "")
          .replace(/_/g, " ");
        groups.push({
          key: s.posKey,
          label,
          kind: s.kind,
          pts: DB.positions[s.posKey]
        });
      }
    }
    return groups;
  }

  function sourcesCard(it) {
    if (!it.sources) return "";
    const groups = collectMapGroups(it);
    const rows = it.sources
      .map(
        (s) => `<tr>
          <td><span class="kindtag ${s.kind}">${s.kind}</span></td>
          <td>${sourceName(s)}</td>
          <td>${chanceText(s)}</td>
          <td>${fmtCount(s.count)}</td>
          <td class="cond">${(s.conditions || []).join("; ") || "—"}</td>
        </tr>`
      )
      .join("");
    const legend = groups
      .map(
        (g, i) =>
          `<span class="li" data-g="${i}"><span class="dot" style="background:${MAP_COLORS[i % MAP_COLORS.length]}"></span>${esc(g.label)} <span class="cond">(${g.pts.length / 2})</span></span>`
      )
      .join("");
    if (groups.length) setTimeout(() => drawMap(groups), 0);
    return `<div class="card wide"><h2>Where to find it</h2>
      <table class="tbl">
        <tr><th></th><th>Source</th><th>Chance</th><th>Count</th><th>Conditions</th></tr>${rows}
      </table>
      ${
        groups.length
          ? `<div class="spawnmap">
        <div class="spawnmap-head">
          <span class="spawnmap-title">Spawn map</span>
          <span class="spawnmap-hint">Scroll to zoom · drag to pan · click legend to toggle</span>
          <button type="button" class="mapbtn" id="mapreset">Reset view</button>
        </div>
        <div id="mapwrap">
          <canvas id="map" width="900" height="720"></canvas>
          <div class="mapoverlay" id="maphover"></div>
        </div>
        <div class="maplegend" id="maplegend">${legend}</div>
      </div>`
          : ""
      }
      <div class="note">Ground sources: each spawn point first rolls its fill chance, then picks one weighted entry from eligible pools. Containers roll N times per restock. Map shows POI outlines from Z1_POIs.json and spawn points from Z1_items / Z1_lootableProps.</div>
    </div>`;
  }

  function ammoForCard(it) {
    if (!it.ammoFor) return "";
    const named = it.ammoFor.filter((id) => byId.get(id));
    if (!named.length) return "";
    return `<div class="card"><h2>Used by weapons</h2>
      <div class="chips">${named.map((id) => `<span class="chip">${link(id)}</span>`).join("")}</div>
    </div>`;
  }

  // ------------------------------------------------------------------
  // Map
  // ------------------------------------------------------------------
  const MAP_COLORS = ["#d9a743", "#7fb069", "#6a9fd8", "#c65f5f", "#a883d8", "#5fc6b8", "#d8d86a", "#d86ab8"];
  const POI_FILL = {
    high_tier: "rgba(198, 95, 95, 0.18)",
    military: "rgba(198, 95, 95, 0.22)",
    residential: "rgba(106, 159, 216, 0.16)",
    commercial: "rgba(217, 167, 67, 0.14)",
    rural: "rgba(127, 176, 105, 0.14)",
    industrial: "rgba(168, 131, 216, 0.16)"
  };
  const POI_STROKE = {
    high_tier: "rgba(198, 95, 95, 0.55)",
    military: "rgba(198, 95, 95, 0.65)",
    residential: "rgba(106, 159, 216, 0.5)",
    commercial: "rgba(217, 167, 67, 0.5)",
    rural: "rgba(127, 176, 105, 0.5)",
    industrial: "rgba(168, 131, 216, 0.5)"
  };

  function poiStyle(tags) {
    for (const t of ["military", "high_tier", "industrial", "commercial", "residential", "rural"]) {
      if (tags.includes(t)) return { fill: POI_FILL[t], stroke: POI_STROKE[t] };
    }
    return { fill: "rgba(136,145,160,0.12)", stroke: "rgba(136,145,160,0.4)" };
  }

  function drawMap(groups) {
    const canvas = $("#map");
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    const EXT = DB.meta.mapExtent || 4096;
    const off = new Set();
    let scale = 1;
    let panX = 0;
    let panY = 0;
    let dragging = false;
    let lastX = 0;
    let lastY = 0;
    const hoverEl = $("#maphover");

    const worldToScreen = (wx, wz) => {
      const nx = (wx + EXT) / (2 * EXT);
      const ny = 1 - (wz + EXT) / (2 * EXT);
      return {
        x: nx * canvas.width * scale + panX,
        y: ny * canvas.height * scale + panY
      };
    };

    function drawBase() {
      const W = canvas.width;
      const H = canvas.height;
      // terrain wash
      const grad = ctx.createRadialGradient(W / 2, H / 2, 40, W / 2, H / 2, W * 0.7);
      grad.addColorStop(0, "#1a2218");
      grad.addColorStop(0.55, "#141a16");
      grad.addColorStop(1, "#0c1012");
      ctx.fillStyle = grad;
      ctx.fillRect(0, 0, W, H);

      // grid (A–H / 1–8 style)
      ctx.save();
      ctx.translate(panX, panY);
      ctx.scale(scale, scale);
      const cell = W / 8;
      ctx.strokeStyle = "rgba(255,255,255,0.05)";
      ctx.lineWidth = 1 / scale;
      ctx.font = `${11 / scale}px Segoe UI, sans-serif`;
      ctx.fillStyle = "rgba(136,145,160,0.45)";
      ctx.textAlign = "center";
      ctx.textBaseline = "middle";
      for (let i = 0; i <= 8; i++) {
        const p = i * cell;
        ctx.beginPath(); ctx.moveTo(p, 0); ctx.lineTo(p, H); ctx.stroke();
        ctx.beginPath(); ctx.moveTo(0, p); ctx.lineTo(W, p); ctx.stroke();
      }
      for (let col = 0; col < 8; col++) {
        for (let row = 0; row < 8; row++) {
          const letter = String.fromCharCode(65 + col);
          ctx.fillText(letter + (row + 1), col * cell + cell / 2, row * cell + cell / 2);
        }
      }

      // POI polygons
      for (const poi of DB.pois || []) {
        const style = poiStyle(poi.tags || []);
        for (const poly of poi.bounds || []) {
          if (poly.length < 6) continue;
          ctx.beginPath();
          for (let i = 0; i < poly.length; i += 2) {
            const nx = ((poly[i] + EXT) / (2 * EXT)) * W;
            const ny = (1 - (poly[i + 1] + EXT) / (2 * EXT)) * H;
            if (i === 0) ctx.moveTo(nx, ny);
            else ctx.lineTo(nx, ny);
          }
          ctx.closePath();
          ctx.fillStyle = style.fill;
          ctx.fill();
          ctx.strokeStyle = style.stroke;
          ctx.lineWidth = 1.5 / scale;
          ctx.stroke();
        }
      }
      ctx.restore();

      // border
      ctx.strokeStyle = "#2c3340";
      ctx.lineWidth = 2;
      ctx.strokeRect(1, 1, W - 2, H - 2);
    }

    function drawPoints() {
      groups.forEach((g, i) => {
        if (off.has(i)) return;
        const n = g.pts.length / 2;
        ctx.fillStyle = MAP_COLORS[i % MAP_COLORS.length];
        ctx.globalAlpha = n > 4000 ? 0.35 : n > 800 ? 0.55 : 0.9;
        const r = Math.max(1.4, (n > 4000 ? 1.4 : n > 800 ? 2 : 2.8) * Math.sqrt(scale));
        for (let p = 0; p < g.pts.length; p += 2) {
          const s = worldToScreen(g.pts[p], g.pts[p + 1]);
          if (s.x < -4 || s.y < -4 || s.x > canvas.width + 4 || s.y > canvas.height + 4) continue;
          ctx.beginPath();
          ctx.arc(s.x, s.y, r, 0, Math.PI * 2);
          ctx.fill();
        }
      });
      ctx.globalAlpha = 1;
    }

    function draw() {
      ctx.setTransform(1, 0, 0, 1, 0, 0);
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      drawBase();
      drawPoints();
    }

    function fitToSpawns() {
      let minX = Infinity, maxX = -Infinity, minZ = Infinity, maxZ = -Infinity;
      let any = false;
      groups.forEach((g, i) => {
        if (off.has(i)) return;
        for (let p = 0; p < g.pts.length; p += 2) {
          any = true;
          minX = Math.min(minX, g.pts[p]);
          maxX = Math.max(maxX, g.pts[p]);
          minZ = Math.min(minZ, g.pts[p + 1]);
          maxZ = Math.max(maxZ, g.pts[p + 1]);
        }
      });
      if (!any) {
        scale = 1; panX = 0; panY = 0; return;
      }
      const pad = 400;
      minX -= pad; maxX += pad; minZ -= pad; maxZ += pad;
      const spanX = Math.max(maxX - minX, 800);
      const spanZ = Math.max(maxZ - minZ, 800);
      const sx = (2 * EXT) / spanX;
      const sz = (2 * EXT) / spanZ;
      scale = Math.min(sx, sz, 6);
      const cx = (minX + maxX) / 2;
      const cz = (minZ + maxZ) / 2;
      const mid0 = {
        x: ((cx + EXT) / (2 * EXT)) * canvas.width * scale,
        y: (1 - (cz + EXT) / (2 * EXT)) * canvas.height * scale
      };
      panX = canvas.width / 2 - mid0.x;
      panY = canvas.height / 2 - mid0.y;
    }

    fitToSpawns();
    draw();

    $("#maplegend").addEventListener("click", (ev) => {
      const li = ev.target.closest(".li");
      if (!li) return;
      const i = +li.dataset.g;
      if (off.has(i)) { off.delete(i); li.classList.remove("off"); }
      else { off.add(i); li.classList.add("off"); }
      draw();
    });

    $("#mapreset")?.addEventListener("click", () => {
      fitToSpawns();
      draw();
    });

    canvas.addEventListener("wheel", (ev) => {
      ev.preventDefault();
      const rect = canvas.getBoundingClientRect();
      const mx = ((ev.clientX - rect.left) / rect.width) * canvas.width;
      const my = ((ev.clientY - rect.top) / rect.height) * canvas.height;
      const factor = ev.deltaY > 0 ? 0.9 : 1.1;
      const next = Math.min(8, Math.max(0.6, scale * factor));
      // zoom toward cursor
      panX = mx - (mx - panX) * (next / scale);
      panY = my - (my - panY) * (next / scale);
      scale = next;
      draw();
    }, { passive: false });

    canvas.addEventListener("mousedown", (ev) => {
      dragging = true;
      lastX = ev.clientX;
      lastY = ev.clientY;
      canvas.classList.add("dragging");
    });
    window.addEventListener("mouseup", () => {
      dragging = false;
      canvas.classList.remove("dragging");
    });
    window.addEventListener("mousemove", (ev) => {
      if (!dragging) return;
      const rect = canvas.getBoundingClientRect();
      const sx = canvas.width / rect.width;
      const sy = canvas.height / rect.height;
      panX += (ev.clientX - lastX) * sx;
      panY += (ev.clientY - lastY) * sy;
      lastX = ev.clientX;
      lastY = ev.clientY;
      draw();
    });

    canvas.addEventListener("mousemove", (ev) => {
      if (dragging || !hoverEl) return;
      const rect = canvas.getBoundingClientRect();
      const mx = ((ev.clientX - rect.left) / rect.width) * canvas.width;
      const my = ((ev.clientY - rect.top) / rect.height) * canvas.height;
      // convert screen -> world
      const wx = ((mx - panX) / (canvas.width * scale)) * (2 * EXT) - EXT;
      const wz = EXT - ((my - panY) / (canvas.height * scale)) * (2 * EXT);
      let hit = null;
      let best = 40 / scale;
      groups.forEach((g, i) => {
        if (off.has(i)) return;
        for (let p = 0; p < g.pts.length; p += 2) {
          const dx = g.pts[p] - wx;
          const dz = g.pts[p + 1] - wz;
          const d = Math.hypot(dx, dz);
          if (d < best) {
            best = d;
            hit = { g, x: g.pts[p], z: g.pts[p + 1] };
          }
        }
      });
      if (hit) {
        hoverEl.style.display = "block";
        hoverEl.style.left = ev.clientX - rect.left + 12 + "px";
        hoverEl.style.top = ev.clientY - rect.top + 12 + "px";
        hoverEl.textContent = `${hit.g.label}  (${hit.x}, ${hit.z})`;
      } else {
        hoverEl.style.display = "none";
      }
    });
    canvas.addEventListener("mouseleave", () => {
      if (hoverEl) hoverEl.style.display = "none";
    });
  }

  // ------------------------------------------------------------------
  // Pages
  // ------------------------------------------------------------------
  function itemPage(id) {
    const it = byId.get(id);
    if (!it) { content.innerHTML = `<div class="home"><h1>Item #${id} not found</h1></div>`; return; }
    renderSidebar(it.cat);
    document.title = it.name + " — H1Emu Loot Database";
    const about = kv([
      ["Item ID", it.id],
      ["Class", it.cls ? esc(it.cls) : undefined],
      ["Stack size", it.stack > 1 ? it.stack : undefined],
      ["Bulk", it.bulk],
      ["Model", it.model ? `<small>${esc(it.model)}</small>` : undefined]
    ]);
    content.innerHTML = `
      <div class="itemhead">
        <h1>${esc(it.name)}</h1>
        <span class="badge ${esc(it.cat.split(" ")[0])}">${esc(it.cat)}</span>
        ${it.code ? `<span class="code">${esc(it.code)}</span>` : ""}
      </div>
      ${it.desc ? `<p class="desc">${esc(it.desc)}</p>` : ""}
      <div class="grid">
        <div class="card"><h2>About</h2>${about}</div>
        ${it.weapon ? weaponCard(it) : ""}
        ${it.melee ? meleeCard(it) : ""}
        ${it.use ? useCard(it) : ""}
        ${repairCard(it)}
        ${craftCard(it)}
        ${ammoForCard(it)}
        ${sourcesCard(it)}
      </div>`;
    window.scrollTo(0, 0);
  }

  function catPage(cat) {
    renderSidebar(cat);
    document.title = cat + " — H1Emu Loot Database";
    const list = DB.items
      .filter((i) => i.cat === cat)
      .sort((a, b) => (!!b.sources - !!a.sources) || a.name.localeCompare(b.name));
    content.innerHTML = `<div class="home"><h1>${esc(cat)} <span class="cond">(${list.length})</span></h1></div>
      <div class="itemlist">${list
        .map(
          (i) =>
            `<a class="itemcard" href="#/item/${i.id}">
              <div class="nm">${esc(i.name)}</div>
              <div class="sub">#${i.id}${i.sources ? ` · ${i.sources.length} loot source${i.sources.length > 1 ? "s" : ""}` : ""}${i.craftedBy ? " · craftable" : ""}</div>
            </a>`
        )
        .join("")}</div>`;
    window.scrollTo(0, 0);
  }

  function homePage() {
    renderSidebar(null);
    document.title = "H1Emu Loot Database";
    const lootable = DB.items.filter((i) => i.sources).length;
    const craftable = DB.items.filter((i) => i.craftedBy).length;
    const guns = DB.items.filter((i) => i.weapon).length;
    const examples = [10, 2, 1429, 1436, 78, 1467]
      .map((id) => byId.get(id))
      .filter(Boolean);
    content.innerHTML = `<div class="home">
      <h1>H1Emu Loot Database</h1>
      <p class="desc">Searchable item database generated straight from the h1z1-server code and data files — damage, fire rates, loot tables, world spawn points, recipes and repair info reflect exactly what the server does.</p>
      <div class="statrow">
        <div class="stat"><div class="big">${DB.meta.itemCount}</div><div class="lbl">items</div></div>
        <div class="stat"><div class="big">${lootable}</div><div class="lbl">obtainable as loot</div></div>
        <div class="stat"><div class="big">${craftable}</div><div class="lbl">craftable</div></div>
        <div class="stat"><div class="big">${guns}</div><div class="lbl">guns</div></div>
      </div>
      <h2 style="font-size:1rem;color:var(--muted)">Try these:</h2>
      <div class="itemlist">${examples
        .map(
          (i) =>
            `<a class="itemcard" href="#/item/${i.id}"><div class="nm">${esc(i.name)}</div><div class="sub">${esc(i.cat)}</div></a>`
        )
        .join("")}</div>
      <div class="note">Data sources: ${Object.values(DB.meta.sources).map(esc).join(" · ")}<br>
      Regenerate with <code>npx tsx tools/loot-wiki/extract.ts</code> after changing server data.</div>
    </div>`;
  }

  function route() {
    const h = location.hash || "#/";
    let m;
    if ((m = h.match(/^#\/item\/(\d+)/))) itemPage(parseInt(m[1]));
    else if ((m = h.match(/^#\/cat\/(.+)/))) catPage(decodeURIComponent(m[1]));
    else homePage();
  }
  window.addEventListener("hashchange", () => {
    searchEl.value = "";
    currentResults = [];
    resultsEl.classList.add("hidden");
    route();
  });
  route();
})();
